# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
name: Node - Develop

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [12.x, 14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
          npm install -g yarn
      - name: Install
        run: yarn
      - name: Test
        run: yarn test
      - name: Codecov
        if: matrix.os == 'ubuntu-latest'
        uses: codecov/codecov-action@v1.0.12
